resources:
- repo: self
phases:
- phase: Windows
  queue: Hosted VS2017
  steps:
  - template: Build/steps.yml
    parameters:
      buildOs: 'Windows'

- phase: Linux
  queue: Hosted Linux Preview
  steps:
  - template: Build/steps.yml
    parameters:
      buildOs: 'Linux'
      preBuildSteps:
      - task: ms-devlabs.utilitytasks.task-Shellpp.Shell++@0
        displayName: Install Mono
        inputs:
          type: InlineScript
          script: |  

            echo "Installing Mono"
            sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
            sudo apt install apt-transport-https
            echo "deb https://download.mono-project.com/repo/ubuntu stable-xenial main" | sudo tee /etc/apt/sources.list.d/mono-official-stable.list
            sudo apt update
            sudo apt-get -yq install mono-devel

- phase: macOS
  queue: Hosted macOS Preview
  steps:
  - template: Build/steps.yml
    parameters:
      buildOs: 'macOS'
